### ISSUE TITLE
Fails on OS X

### ISSUE THREAD

**Issue by mjperrone** [instant-markdown/instant-markdown-d#13]
file test.markdown:

```
dot_files
=========

My unix dot files
```

```
$ cat test.markdown | instant-markdown-d
Option log level is not valid. Please refer to the README.
connection established!
```

But the body of the html served is empty.

I believe I've installed this correctly. To verify that, what other kind of debugging info would be helpful for me to provide?

**Comment by zhcalvin** [comment]
reinstall it with this repo: `npm install -g git+https://github.com/zhcalvin/instant-markdown-d`, which just downgrades `socket.io` to `0.9`.

**Comment by MichaelMa2014** [comment]
@zhcalvin This command gives me "permission denied" even when I run it with `sudo`. Could you please explain to me why? I am completely new to Node. Thanks!

**Comment by ashwinvis** [comment]
CI includes tests in macOS as well. If there are any issues, run the test suites using `pytest` and report the logs. Closing.
