### ISSUE TITLE
TypeError: Cannot read property 'emit' crash

### ISSUE THREAD

**Issue by seekingThat** [instant-markdown/instant-markdown-d#47]
Hi,

While checking why markdown is not working and running one of your testcases resulted in a crash as soon as curl was started in another window. instant-markdown-d is the latest. Following is the input:

% echo lala | instant-markdown-d
Option log level is not valid. Please refer to the README.
/usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d:40
output.emit('newContent', md.render(body));
^

TypeError: Cannot read property 'emit' of undefined
at IncomingMessage. (/usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d:40:11)
at emitNone (events.js:67:13)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickCallback (node.js:355:17)

% echo abcdefg | curl -X PUT -T - http://localhost:8090

web-server didn't get started and I didn't see the output of testing.md file. I would be happy to provide any inputs required to solve this problem. Thanks!

**Comment by MichaelMa2014** [comment]
Same problem here. Please help!

**Comment by ashwinvis** [comment]
Not sure what was wrong, but it is longer an issue :)
