### ISSUE TITLE
Tables in a list require preceding blank line on GitHub

### ISSUE THREAD

**Issue by schlueter** [instant-markdown/instant-markdown-d#57]
For example, this markdown:

    1. Configure the fields as follows:
        | Prompt                     | You enter                                        |
        |----------------------------|:------------------------------------------------:|
        | Application Name           | Whatever you'd like                              |
        | Homepage URL               | http://localhost:12345                           |
        | Application Description    | Whatever you'd like or nothing                   |
        | Authorization callback URL | http://localhost:12345/securityRealm/finishLogin |

is rendered by instant-markdown-d as:

    <ol>
        <li>Configure the fields as follows:
            <table>
                <thead>
                    <tr><th>Prompt</th><th style="text-align:center">You enter</th></tr>
                </thead>
                <tbody>
                    <tr><td>Application Name</td><td style="text-align:center">Whatever you'd like</td></tr>
                    <tr><td>Homepage URL</td><td style="text-align:center"><a href="http://localhost:12345">http://localhost:12345</a></td></tr>
                    <tr><td>Application Description</td><td style="text-align:center">Whatever you'd like or nothing</td></tr>
                    <tr><td>Authorization callback URL</td><td style="text-align:center"><a href="http://localhost:12345/securityRealm/finishLogin">http://localhost:12345/securityRealm/finishLogin</a></td></tr>
                </tbody>
            </table>
        </li>
    </ol>

but by GitHub as:

    <ol>
    <li>Configure the fields as follows:<br>
    | Prompt                     | You enter                                        |<br>
    |----------------------------|:------------------------------------------------:|<br>
    | Application Name           | Whatever you'd like                              |<br>
    | Homepage URL               | <a href="http://localhost:12345" rel="nofollow">http://localhost:12345</a>                           |<br>
    | Application Description    | Whatever you'd like or nothing                   |<br>
    | Authorization callback URL | <a href="http://localhost:12345/securityRealm/finishLogin" rel="nofollow">http://localhost:12345/securityRealm/finishLogin</a> |</li>
    </ol>

With an additional empty newline before the table, GitHub will render the table indented with the list item.

**Comment by ashwinvis** [comment]
I confirm. Strange JS bug indeed.

**Comment by ashwinvis** [comment]
Fixed in version 0.2.0
