### ISSUE TITLE
Feature Enhancement 

### ISSUE THREAD

**Issue by vijaykarani333** [instant-markdown/instant-markdown-d#72]
# Feature Enhancement summary
http://localhost:8090/ can't work vim-like browser plug in.

vim-like : Vimium 
https://github.com/philc/vimium

## Expected
Since the "preview" is open in the browser, how can we set up instant-markdown-d work with browser?

## Environment Information

 * OS and version: macOS Mojave, 10.14.6
 * Vim / Neovim version:  version 8.2.1800  
 * Browser and version: Firefox 85.0b4 (64-bit)

**Comment by ashwinvis** [comment]
This is a Vimium issue. Have you excluded `localhost` in Vimium preferences? For me it is this URL:

moz-extension://c18f7f52-b3c4-416a-9bbc-fce52fa12c6a/pages/options.html

Another option is to install qutebrowser and call `instant-markdown-d --browser qutebrowser ...`.
