### ISSUE TITLE
NPM last version with socket.io v2 = Chrome CORS error (solved in master branch)

### ISSUE THREAD

**Issue by lucascebertin** [instant-markdown/instant-markdown-d#80]
# Npm last version published does not have socket.io v3 as master, Chrome complains about CORS without it

## Expected
Start server will spawn a Chrome instance and the transport layer works properly, showing the markdown rendered.

I just removed the pull request template because using the `master` branch directly works properly, is it possible to publish master as `@next` at npm?

If more info needed, no problem, I can get back and share that with you.

**Comment by ashwinvis** [comment]
We had some reports in #77 and #79 that the package may not be compatible with latest node... Could you share the output of `node --version`?

**Comment by ashwinvis** [comment]
After a week worth of proper testing and ~2 year long wait, version 0.2.0 is published!
