### ISSUE TITLE
The plug can't produce id for title

### ISSUE THREAD

**Issue by wuxinyiwu** [instant-markdown/instant-markdown-d#88]
# Problem summary
The plug can't produce id for title
## Environment Information

 * OS:windows7
 * Vim / Neovim version:vim8.1.24
 * Browser:firefox

## Steps to reproduce the issue (required)

Start with command you used to install `instant-markdown-d`. Use [a
minimal.vimrc](https://raw.githubusercontent.com/instant-markdown/vim-instant-markdown/master/doc/minimal.vimrc)
to reproduce the issue and open your markdown file as:

```sh
vim -u minimal.vimrc my_markdown_file.md
```

 1.
 2.
 3.

## Provide the debug output (required)

Run `cat my_markdown_file.md | instant-markdown-d --mathjax --debug`. It
generates a `debug.html` file - attach it here. Also, paste the console output
here:

```sh

```

## Screen shot (if possible)

![1630074819(1)](https://user-images.githubusercontent.com/32120035/131144006-fb6c4828-c999-40dc-a3fb-5b086f576545.jpg)

**Comment by ashwinvis** [comment]
I see. See also https://www.npmjs.com/package/markdown-it-table-of-contents/

**Comment by ashwinvis** [comment]
Somebody added support for this in #103
