### ISSUE TITLE
Feature Request: could we ignore the YAML meta block in the markdown?

### ISSUE THREAD

**Issue by hitzhangjie** [instant-markdown/instant-markdown-d#93]
# Problem summary

Hi, there're some markdown editors or github, they require or encourage users to write some liquid tags in the document. For example, we could write author, description, tags, then the static site generate like hugo can extract this kind of info to build a static site.

Sometimes, when we edit the file in vim + instant-markdown-d, when rendering, the liquid tags will be treated like normal text. I think we should ignore this part or render it in some fancy way.

## Expected

Ignore the liquid tags or render it in some fancy way.

## Example

here's a markdown with liquid tags:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/3725760/175804376-463207c5-5979-489b-b58d-bc38ca050fdd.png">

it will be rendered like this so far:

![image](https://user-images.githubusercontent.com/3725760/175804446-5661d517-08e8-4b17-8b6b-1f70a1ed1837.png)

**Comment by hitzhangjie** [comment]
If this PR is welcome, I think I could submit a PR.

**Comment by ashwinvis** [comment]
Sure! Contributions welcome.

BTW, I think that is called a YAML metadata block. Liquid tags are a templating system some markdown engines uses.

**Comment by hitzhangjie** [comment]
Yes, it is called a YAML metadata block.

**Comment by ashwinvis** [comment]
Done in #95
